### ISSUE TITLE
Aliases can be directly re-registred after deletion

### ISSUE THREAD

**Issue by t2d** [systemli/user-management#56]
If I delete an alias, another user can directly re-register it. I guess, that's not, what we wanted. Also, there are entries in the database left behind without `user_id`, which will probably never be deleted.

On the other hand:
If we allow users to create and delete aliases, but don't free up aliases after deletion,  1 single user could exhaust the complete namespace by just creating and deleting all (short) addresses.

**Comment by doobry-systemli** [comment]
Oups, that are bugs indeed. The `Alias` entity already has the soft-deletion logic implemented, so apparently the Validator needs to be fixed in a way that it also checks for aliases that have `deleted = true`.

In my eyes we should disallow re-registering of formerly used aliases for now and discuss the other question seperately.

It's true that a user could exhaust the full namespace. The best protection I can come up with, is to implement a total counter of created custom aliases per user and introduce a limit here.
